### PR TITLE
#27 - Refactor System Management Admin page

### LINKED ISSUE #27: System admin page UI/UX
The system admin page could benefit from a rework.  The ability to filter and group by namespaces could be useful, but also rethinking the entire design is really appropriate.

NOTE: this issue is focused on the UI/UX aspect of the page. Improvements in functionality may be side effects of that effort. More in-depth functional issues are tracked in their own tickets.

### PR DESCRIPTION
**Pull request by jessica-obrien**
Closes #27 

Make page contents more condense and easier to view. Refactors out namespace, system, and instance services into hooks.

Follow on tickets to add functionality that seems missing: #86, #87, #88, , #89

### CODE REVIEW

**Comment by scott-taubman** [comment]
I'll leave reviewing the actual code to someone else, but a couple of comments just from playing around with it.

1) I don't feel like there's much value in having the System cards collapsible.  It feels like it just adds an extra click to getting to the controls.  And once you expand one card, you gain nothing from having the others collapsed, because all of the space is taken up anyway.
2) The cards don't gracefully handle long system names.  I got a scrollbar underneath a slightly long name.

The attached screenshot shows an example of both items in action.

Systems Management

**Review by jlrpnbbngtn — CHANGES_REQUESTED** [review]
See comments.

**Review by jlrpnbbngtn — CHANGES_REQUESTED** [review]
See comments

**Review by jlrpnbbngtn — APPROVED** [review]
LGTM

**Pull request merged**
